# Ex 1

## Numpy warmup exercises

### Preamble

In [168]:
import ucamcl
GRADER = ucamcl.autograder('https://markmy.solutions', course='scicomp').subsection('ex1')

Waiting for you to log in .. done.


### Q1

In [92]:
import numpy as np
import math, random
rng = np.random.default_rng(0)

In [93]:
x = rng.uniform(-1, 1, 1000000)
y = rng.uniform(-1, 1, 1000000)
d = np.sqrt(x**2 + y**2)

In [94]:
mean = np.mean(d)
sd = np.std(d)
print(mean, sd)

0.7653788363741706 0.28464670655850516


In [95]:
q = GRADER.fetch_question('q1')
print(q)

# Store x and y as two columns in an n*2 matrix
xy = np.random.uniform(-1,1,size=(1000000,2))
# axis=1 means "compute the norm of each row"
d = np.linalg.norm(xy, axis=1)
{'mean': np.mean(d), 'sd': np.std(d)}


In [96]:
# Store x and y as two columns in an n*2 matrix
xy = rng.uniform(-1,1,size=(1000000,2))
# axis=1 means "compute the norm of each row"
d = np.linalg.norm(xy, axis=1)
{'mean': np.mean(d), 'sd': np.std(d)}

{'mean': 0.76483171015211, 'sd': 0.2845077008574853}

### Q2

In [97]:
x = np.linspace(.1 ,10, 1000)
a = x**2
b = 0.01*(np.exp(x)-1)

print(x[np.argmax(a<b)])

9.00900900900901


In [98]:
q = GRADER.fetch_question('q2')
print(q)

# argmax finds the first occurrence of the maximum of c
c = np.where(a<b, 1, 0)
i = np.argmax(c)
x[i]

# Or, a one-liner, using implicit conversion of boolean to 0/1
x[np.argmax(a<b)]


### Q3

In [99]:
names = np.array(['alexis','chloe','guarav','shay','adrian','rebecca'])
i = np.argsort(names)
print(i)
names_rank = np.char.add(names[i], np.arange(1,7).astype(str))
# j = np.array([1, 2, 3, 5, 0, 4])
# names_rank[j]
print(np.argsort(i))
names_rank[np.argsort(i)]

[4 0 1 2 5 3]
[1 2 3 5 0 4]


array(['alexis2', 'chloe3', 'guarav4', 'shay6', 'adrian1', 'rebecca5'],
      dtype='<U28')

In [100]:
q = GRADER.fetch_question('q3')
print(q)

# Calling np.argsort(i) gives the indexes that put i back in order
# Here i = [4, 0, 1, 2, 5, 3] and names[i] = ['adrian','alexis','chloe',...]
# And argsort(i) = [1, 2, 3, 5, 0, 4] meaning "take element 1, then 2, then ..."
names_rank[np.argsort(i)]


### Q4

In [101]:
# a.shape gives a tuple of dimensions, and the first is len(a)

q = GRADER.fetch_question('q4')
print(q)

a.shape gives the full matrix dimensions, (nrows,ncols).
len(a) gives nrows. (In fact len(a) always gives the first dimension, 
whether it's a vector or a multidimensional array.)


### Q5

In [102]:
vec = np.arange(1, 16)
vec = np.reshape(vec, (3, 5))
colsums = np.sum(vec, axis = 0)
rowsums = np.sum(vec, axis = 1)
# can use -1 for one of the reshape dimensions: infers from the size of the array and the other dimensions

In [103]:
q = GRADER.fetch_question('q5')
print(q)

x = np.arange(1,16).reshape(3,-1)
print("colsums", np.sum(x, axis=0))
print("rowsums", np.sum(x, axis=1))


### Q6

In [124]:
n = 5
np.arange(1, n+1)[:, None]
np.arange(1, n+1).reshape(-1, 1)
np.array([np.arange(1, n+1)]).transpose()

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [113]:
q = GRADER.fetch_question('q6')
print(q)

n = 5
np.arange(1,n+1).reshape(-1,1)
np.array([np.arange(1,n+1)]).T


### Q7

In [129]:
n = 5
cols = rng.permutation(n)
rows = rng.permutation(n)
a = np.zeros((n, n), dtype=int)
a[rows, cols] = np.ones(n)
# Can just use 1 instead on RHS
a

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0]])

In [130]:
q = GRADER.fetch_question('q7')
print(q)

n = 5
# Create a matrix filled with 0
a = np.zeros((n,n), dtype=int)
# Use "integer advanced indexing" to set some elements to 1
a[np.arange(n), np.random.permutation(n)] = 1


### Q8

In [166]:
a = np.array([4,1,2,8,2,3,1])
C = 3
q_0 = 1
x = np.cumsum(a - C)
y = np.minimum.accumulate(q_0 + x)
q = q_0 + x - np.minimum(0, y)
q

array([2, 0, 0, 5, 4, 4, 2])

In [169]:
q = GRADER.fetch_question('q8')
print(q)

a = np.array([4,1,2,8,2,3,1])
q0, C = 1, 3
x = np.cumsum(a - C)
y = np.minimum.accumulate(q0 + x)
q0 + x - np.minimum(0, y)
